#!/bin/sh
# Writes a minimal .env for CI smoke tests (no real Ludus server).
# Docker Compose reads this from the repo root.
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
cat > .env <<'EOF'
# Generated by ci/write-ci-env.sh — do not use in production
LUDUS_SSH_HOST=127.0.0.1
LUDUS_SSH_PORT=22
DISABLE_HTTPS=true
APP_SECRET=ci-smoke-test-secret-min-32-chars-ok
LUDUS_ROOT_API_KEY=
PROXMOX_SSH_PASSWORD=
ENABLE_GOAD=false
EOF
echo "Wrote $ROOT/.env for CI"
