network:
  rules:
    - name: Allow targets to SO Fleet
      vlan_src: 10
      vlan_dst: 20
      protocol: tcp
      ports: "8220"
      action: ACCEPT
    - name: allow-443
      vlan_src: 10
      vlan_dst: 10
      protocol: tcp
      ports: "443"
      action: ACCEPT
